version: '3'
services:
  cairo:
    image: shardlabs/cairo-cli:latest
    container_name: starknet-dev
    # build:
    #   context: .
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./srv:/srv
    command: ["sh"]
    working_dir: /srv
    stdin_open: true # docker run -i
    tty: true        # docker run -t